development:
  adapter: postgresql
  encoding: unicode
  database: seek_development
  pool: 5
  username: jackson
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: seek_test
  pool: 5
  username: jackson
  password: